// packages/widget-svelte/src/lib/widget.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();

  import EmojiScale from "./emoji-scale.svelte";
  import UserInput from "./user-input.svelte";
  import StatusSuccess from "./status-success.svelte";
  import StatusFailure from "./status-failure.svelte";

  export let projectId: string;

  let selectedEmotion: null | 1 | 2 | 3;
  $: selectedEmotion = null;
  let email: null | string;
  let note: null | string;
  let form: HTMLFormElement;
  let submitSuccess: boolean | null;
  $: submitSuccess = null;

  $: if (selectedEmotion) {
    dispatch("emotion-changed", { emotion: selectedEmotion });
  }

  const handleSubmit = async (event: SubmitEvent) => {
    const feedback = {
      type: "feedback",
      payload: {
        emotion: selectedEmotion,
        note,
        email,
      },
      projectId,
    };

    const url = `${window.location.hostname === "localhost" ? "http://localhost:5173" : "https://dash.loopback.works"}/api/feedback`;
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(feedback),
    });

    if (res.ok) {
      submitSuccess = true;
    } else {
      submitSuccess = false;
    }
    form.reset();

    setTimeout(() => {
      selectedEmotion = null;
      email = null;
      note = null;
      submitSuccess = null;
    }, 5000);
  };
</script>

<div
  class="lb-m-auto lb-bg-background lb-text-foreground lb-font-medium loopback-root lb-max-w-md lb-rounded-tr-2xl lb-space-y-6 lb-px-6 lb-py-8"
>
  {#if submitSuccess === true}
    <StatusSuccess />
  {:else if submitSuccess === false}
    <StatusFailure />
  {:else}
    <p class="lb-text-center lb-font-bold">Leave feedback</p>
    <form
      bind:this={form}
      action="post"
      on:submit|preventDefault={handleSubmit}
    >
      {#if selectedEmotion}
        <UserInput bind:selectedEmotion bind:email bind:note />
      {:else}
        <EmojiScale bind:selectedEmotion />
      {/if}
    </form>
  {/if}
  <p class="lb-text-[0.6rem] lb-text-center">
    Powered by{" "}
    <a
      rel="noopener noreferrer"
      target="_blank"
      href="https://loopback.works/"
      class="lb-font-bold"
    >
      Loopback
    </a>
  </p>
</div>

// packages/widget-react/src/lib/Widget/index.tsx
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { zodResolver } from "@hookform/resolvers/zod";
import { IconLoader2, IconSend } from "@tabler/icons-react";
import { Dispatch, SetStateAction, useState } from "react";
import { FormProvider, useForm, useFormContext } from "react-hook-form";
import { EmojiScale } from "./EmojiScale";
import { WidgetFormType, widgetSchema } from "./schema";
import { FailedMessage, SuccessMessage } from "./Status";

type Props = {
	projectId: string;
};
export function LoopbackWidget({ projectId }: Props) {
	const [submitSuccess, setSubmitSuccess] = useState<boolean | null>(null);
	return (
		<div className="lb-m-auto lb-bg-background lb-text-foreground lb-border-border lb-font-medium loopback-root lb-max-w-md lb-rounded-2xl lb-space-y-6 lb-px-6 lb-py-8">
			{submitSuccess === true && <SuccessMessage />}
			{submitSuccess === false && <FailedMessage />}

			{submitSuccess === null && (
				<>
					<p className="lb-text-center lb-font-bold lb-text-black">Leave feedback</p>
					<WidgetForm projectId={projectId} setSuccess={setSubmitSuccess}  />
				</>
			)}
			<p className="lb-text-[0.6rem] lb-text-center">
				Powered by{" "}
				<a
					rel="noopener noreferrer"
					target="_blank"
					href="https://loopback.works/"
					className="lb-font-bold"
				>
					Loopback
				</a>
			</p>
		</div>
	);
}

type WidgetFormProps = {
  projectId: string;
	setSuccess: Dispatch<SetStateAction<boolean | null>>;
};
function WidgetForm({ projectId, setSuccess }: WidgetFormProps) {
	const form = useForm<WidgetFormType>({ resolver: zodResolver(widgetSchema) });

	async function submitFeedback(data: WidgetFormType) {
		const feedback = {
			type: "feedback",
			payload: {
				emotion: data.emotion,
				note: data.note,
				email: data.email,
			},
			projectId,
		};

		const res = await fetch("/api/feedback", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(feedback),
		});

		if (res.ok) {
			setSuccess(true);
		} else {
			setSuccess(false);
		}
		form.reset();

		setTimeout(() => {
			setSuccess(null);
		}, 5000);
	}

	return (
		<FormProvider {...form}>
			<form onSubmit={form.handleSubmit(submitFeedback)} className="lb-space-y-6">
				{form.watch("emotion") ? (
					<UserInput />
				) : (
					<div className="lb-flex lb-justify-center">
						<EmojiScale />
					</div>
				)}
			</form>
		</FormProvider>
	);
}

function UserInput() {
	const {
		register,
		formState: { isSubmitting, errors },
	} = useFormContext<WidgetFormType>();
	return (
		<div className="lb-space-y-4">
			<div className="lb-space-y-2">
				<label
					className="lb-block lb-text-left lb-text-xs lb-uppercase lb-text-black"
					htmlFor="note"
				>
					Note (optional)
				</label>
				<Textarea
					{...register("note")}
					draggable="false"
					autoCapitalize="off"
					autoComplete="off"
					autoCorrect="off"
					placeholder="Your feedback..."
					id="note"
					className="lb-resize-none"
				/>
				{errors.note && (
					<p className="lb-text-xs lb-text-red-600 lb-text-left">{errors.note.message} </p>
				)}
			</div>
			<div className="lb-space-y-2">
				<label
					className="lb-block lb-text-left lb-text-xs lb-uppercase lb-text-black"
					htmlFor="email"
				>
					Email (optional)
				</label>
				<Input {...register("email")} id="email" placeholder="john@doe.com" />
				{errors.email && (
					<p className="lb-text-xs lb-text-red-600 lb-text-left">{errors.email.message} </p>
				)}
			</div>
			<div className="lb-flex lb-justify-between lb-flex-wrap lb-items-center">
				<EmojiScale size="small" />

				<Button
				  type="submit"
					disabled={isSubmitting}
					className="lb-flex lb-w-[100px] lb-items-center lb-gap-2"
					variant="default"
				>
					{isSubmitting ? (
						<IconLoader2 className="lb-animate-spin" />
					) : (
						<>
							Submit
							<IconSend size={16} />
						</>
					)}
				</Button>
			</div>
		</div>
	);
}
