// packages/widget-react-v1/src/components/ui/input.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

export interface InputProps
  extends React.InputHTMLAttributes<HTMLInputElement> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "lb-flex lb-h-10 lb-w-full lb-rounded-md lb-border lb-border-input lb-bg-background lb-px-3 lb-py-2 lb-text-sm lb-ring-offset-background file:lb-border-0 file:lb-bg-transparent file:lb-text-sm file:lb-font-medium placeholder:lb-text-muted-foreground focus-visible:lb-outline-none focus-visible:lb-ring-2 focus-visible:lb-ring-ring focus-visible:lb-ring-offset-2 disabled:lb-cursor-not-allowed disabled:lb-opacity-50",
          className
        )}
        ref={ref}
        {...props}
      />
    )
  }
)
Input.displayName = "Input"

export { Input }

// packages/widget-svelte-v1/src/lib/components/ui/input/input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from "svelte/elements";
	import type { InputEvents } from "./index.js";
	import { cn } from "$lib/utils.js";

	type $$Props = HTMLInputAttributes;
	type $$Events = InputEvents;

	let className: $$Props["class"] = undefined;
	export let value: $$Props["value"] = undefined;
	export { className as class };

	// Workaround for https://github.com/sveltejs/svelte/issues/9305
	// Fixed in Svelte 5, but not backported to 4.x.
	export let readonly: $$Props["readonly"] = undefined;
</script>

<input
	class={cn(
		"lb-border-input lb-bg-background lb-ring-offset-background placeholder:lb-text-muted-foreground focus-visible:lb-ring-ring lb-flex lb-h-10 lb-w-full lb-rounded-md lb-border lb-px-3 lb-py-2 lb-text-sm file:lb-border-0 file:lb-bg-transparent file:lb-text-sm file:lb-font-medium focus-visible:lb-outline-none focus-visible:lb-ring-2 focus-visible:lb-ring-offset-2 disabled:lb-cursor-not-allowed disabled:lb-opacity-50",
		className
	)}
	bind:value
	{readonly}
	on:blur
	on:change
	on:click
	on:focus
	on:focusin
	on:focusout
	on:keydown
	on:keypress
	on:keyup
	on:mouseover
	on:mouseenter
	on:mouseleave
	on:mousemove
	on:paste
	on:input
	on:wheel|passive
	{...$$restProps}
/>
